Insert RSA
YaccConstructor/YC_in_Coq pull request #6
Opened 2017-08-04 09:43 UTC by MallabaevAzamat

Please, no close pr

2017-08-04 09:52 UTC, gsvgit requested changes

2017-08-04 09:52 UTC, gsvgit commented on CFGINT/Base.v
> +Definition ISectFSA Vt Et (a b: FSA Vt Et): FSA Vt Et := fun (vb: Vt) (e: Et) (ve: Vt) => (a vb e ve) /\ (b vb e ve).
Если нужны какие-то часть FSA, то надо взять работу смолки по конечным автоматам. Спросите у ребят в слэке. Скажцут, где взять исходники. И, возможно, кто-нибудь уж перетянул её к нам.

2017-08-04 09:52 UTC, gsvgit commented on CFGINT/Base.v
> +	Nu: Nt -> (St * St) -> Prop;
Можете более говорящие названия давать? Я даже по смыслу с трудом догадываюсь, что такое Nu.

2017-08-04 09:52 UTC, gsvgit commented on CFGINT/Base.v
> +Definition ISectRSA {Tt Nt St} (a b: RSA Tt Nt St): RSA Tt Nt St := mkRSA Tt Nt St (ISectFSA St (Tt + Nt) (a.(Aut Tt Nt St)) (b.(Aut Tt Nt St))) (fun n p => (Nu Tt Nt St a) n p \/ (Nu Tt Nt St b) n p
Имена. Не очень понимаю, почему таоке название у определения.

2017-08-14 10:16 UTC, MallabaevAzamat commented on CFGINT/Base.v
> +Definition ISectRSA {Tt Nt St} (a b: RSA Tt Nt St): RSA Tt Nt St := mkRSA Tt Nt St (ISectFSA St (Tt + Nt) (a.(Aut Tt Nt St)) (b.(Aut Tt Nt St))) (fun n p => (Nu Tt Nt St a) n p \/ (Nu Tt Nt St b) n p
I`nter`Sect`ion` `of` R`egular`S`tate`A`utomat`

2017-08-14 10:18 UTC, MallabaevAzamat commented on CFGINT/Base.v
> +Definition ISectFSA Vt Et (a b: FSA Vt Et): FSA Vt Et := fun (vb: Vt) (e: Et) (ve: Vt) => (a vb e ve) /\ (b vb e ve).
На самом деле не нужно, просто пересечение в любом случае отталкивается от регулярной части

2017-08-14 10:19 UTC, MallabaevAzamat commented on CFGINT/Base.v
> +	Nu: Nt -> (St * St) -> Prop;
Nu -- греческая буква, просто созвучна с N`onterminal`

2017-08-14 10:20 UTC, MallabaevAzamat commented on CFGINT/Base.v
> +Definition ISectRSA {Tt Nt St} (a b: RSA Tt Nt St): RSA Tt Nt St := mkRSA Tt Nt St (ISectFSA St (Tt + Nt) (a.(Aut Tt Nt St)) (b.(Aut Tt Nt St))) (fun n p => (Nu Tt Nt St a) n p \/ (Nu Tt Nt St b) n p
Однако, действительно лучше не сокращать

2017-08-15 06:47 UTC, gsvgit requested changes
Не надо делать лишнего. Координируйте свои действия с остальной группой. 
GLL лишний. Отсутствует определение рекурсивного автомата без рекурсивных вызовов. Проще всего таоке сделать -- построить граф вызовов и сказать, что в нём нет циклов.

2017-08-15 06:47 UTC, gsvgit commented on CFGINT/Definitions.v
> +Section Input_Definition.
Вход есть в части про CFG. Надо переиспользовать общие части.

2017-08-15 06:47 UTC, gsvgit commented on CFGINT/Definitions.v
> +Section GLL_Definition.
Я чатик в слэке не просто так создавал. GLL-ем сейчас Сегрей занимается. Не деалйте лишнего. Общайтесь с ребятами, координируйте действия. 

Отдельно. Мешать GLL и RSA в одни файл -- плохое решение.

2017-08-15 06:47 UTC, gsvgit commented on CFGINT/Definitions.v
> +  Section FSA_Intersection.
Нужно переиспользовать существующие конечные автоматы.

2017-08-15 06:47 UTC, gsvgit commented on CFGINT/Base.v
> +	Nu: Nt -> (St * St) -> Prop;
Давайте нормальные названия сущностям.

2017-08-16 08:42 UTC, gsvgit commented
И так. Исправить замечания, удалить всё лишнее. Оформить аккуратный модуль с рекурсивными автоматами.

2017-08-22 13:26 UTC, GKerfImf commented on CFGINT/Definitions.v
> +  Definition states : Ensemble Q := Full_set Q.
Определения и теоремы лучше разбить по разным секциям

2017-11-20 16:29 UTC, merged